version: "3.8
"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - /absolute/path/to/mongo-db/data/db:/data/db
    networks:
      - app-network


  boot-app:

    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/food-app

    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-db:
networks:
  app-network:




